Question.create!([
  {question: "Fill in the Blank: In 2008, Alumnus David G. Booth donated ___ million dollars to the University of Chicago's School of Business.", answer: "300", answer_explanation: "Chicago Booth is the second-oldest business school in the U.S., with the third-largest endowment of any business school.", user_id: 1, chat_room_id: 4, state: 1},
  {question: "The M7 (also known as the Magnificent 7 and Magic 7) is a set of elite business schools consisting of: U Chicago (Booth), Harvard (HBS), Stanford (Stanford GSB), U Penn (Wharton), MIT (Sloan), Northwestern (Kellog).  Which univeristy is missing from this list?", answer: "Columbia", answer_explanation: "The designation itself — M7, standing for Magnificent 7 or Magic 7 — is self-given, and therein lies the source of a long-running, probably inextinguishable dispute. Many feel it should be the Terrific 10, including Dartmouth College’s Tuck School of Business, UC-Berkeley’s Haas School, and Duke University’s Fuqua School of Business; the rankings lately certainly reflect that. For that matter, you could add another couple of names — Yale SOM, in particular. The M7 modality, set in stone after a legendary meeting of the seven schools’ deans many years ago, is more than just shorthand for greatness. It affects interactions at every level of the seven schools and other schools that do business with them. It impacts more than the twice-yearly meetings among the seven deans — it also impacts meetings among vice deans, admission directors, career management directors, even PR and marketing types.", user_id: 1, chat_room_id: 4, state: 1},
  {question: "As of 2018, the THIRD largest recruiter of Booth students, in terms of full-time offers accepted after graduation, is...?", answer: "Boston Consulting Group", answer_explanation: "#1 McKinsey.  #2 - Amazon", user_id: 1, chat_room_id: 4, state: 1},
  {question: "As of 2018, how many Nobel Laureates are at the Chicago Booth School of Business?", answer: "9", answer_explanation: "George Stigler (1982), Merton Miller (1990), Ronald Coase (1991), Gary Becker (1992), Robert Fogel (1993), Myron Scholes (1997), Eugene Fama (2013), Lars Peter Hansen (2013), Richard Thaler (2017)", user_id: 1, chat_room_id: 4, state: 1},
  {question: "3*1?", answer: "3", answer_explanation: "", user_id: 1, chat_room_id: 6, state: 1},
  {question: "2+2?", answer: "4", answer_explanation: "", user_id: 1, chat_room_id: 6, state: 1}
])
ChatRoom.create!([
  {title: "General Trivia", user_id: 1, state: 0, description: "Designed just for fun."},
  {title: "Fast Math", user_id: 1, state: 0, description: nil}
])